name: The Foundry
favicon: null
layout_spectrum: 0.5958365155383945
typography_spectrum: 0.6600202270783484
title: 'The Foundry | Modern American Kitchen'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6918644972611219
  lightness: 0.615153328049928
  saturation: 0.6976995256263763
  rhythmicContrast: 0.11335743078961968
purpose: []
