name: The Foundry
favicon: null
layout_spectrum: 0.5958365155383945
typography_spectrum: 0.6600202270783484
title: 'The Foundry | Modern American Kitchen'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#181415'
    - '#483e3c'
    - '#857b7a'
    - '#b8a6a2'
    - '#faf8e7'
  brandStrength: 0.8125
  lightness: 0.625
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
